import Header from "@/app/_components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/app/_components/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Facebook Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <main className="flex bg-gray-100">
          {/* left sidebar */}
          <Sidebar></Sidebar>
          {/* main container */}
          {children}
          {/* right sidebar */}
        </main>
      </body>
    </html>
  );
}
